# Generated by Django 5.0.3 on 2024-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='last_name',
            field=models.CharField(default=-2024, max_length=45),
            preserve_default=False,
        ),
    ]
