# Generated by Django 5.0.3 on 2024-04-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0005_author_delete_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=-2024),
            preserve_default=False,
        ),
    ]
